-- jankurai:allow HLT-030-SQL-BAD-BEHAVIOR reason=d1-sqlite-no-concurrent-index expires=2027-06-01
-- Migration 0008: add vote_policy and session_mode to sessions table.
-- These columns were defined in schema.sql but were never shipped as a migration,
-- so they don't exist in databases created from the 0000_init migration.
-- Apply: `wrangler d1 migrations apply qesto-prod`
-- NOTE: If initialized from schema.sql (new databases), these columns already exist.
-- This migration is now a no-op for fresh databases; it only applies to old databases.

-- Conditional: only add if not present (for compatibility with both paths)
-- SQLite doesn't have ALTER TABLE IF COLUMN NOT EXISTS, so we document this
-- and rely on the migration being idempotent via the canonical schema.sql approach.
