-- 0066_studio_library.sql
-- STUDIO-LIBRARY-01 (ADR-0060, S97) — persistent content library for the STUDIO
-- authoring co-pilot. Drafts generated by `lib/studio-authoring.ts` are ephemeral
-- today; this table lets an operator SAVE a validated authored question, LIST the
-- team's library, FORK an existing item into an independent copy, and DELETE it.
--
-- Tenant-scoped: every row carries team_id and every read/write is scoped to the
-- caller's team. Cross-tenant fork is explicitly OUT OF SCOPE this sprint (deferred
-- to a future CONNECT-gated sprint per SPRINT97_EXECUTION.md "Out of scope").

CREATE TABLE IF NOT EXISTS studio_library_items (
  id             TEXT PRIMARY KEY,                 -- uuid
  team_id        TEXT NOT NULL,                    -- owning tenant (isolation boundary)
  created_by     TEXT NOT NULL,                    -- user id of the saver/forker
  source         TEXT NOT NULL DEFAULT 'authored'  -- provenance
                 CHECK (source IN ('authored', 'fork')),
  forked_from_id TEXT,                             -- nullable self-FK: original item this was forked from
  question_json  TEXT NOT NULL,                    -- validated question payload (AIQuestionSchema shape)
  theme_id       TEXT,                             -- nullable CANVAS theme id applied at authoring time
  title          TEXT NOT NULL,                    -- topic/title for list display
  use_count      INTEGER NOT NULL DEFAULT 0,       -- incremented on the original each time it is forked
  created_at     INTEGER NOT NULL,                 -- unix ms
  updated_at     INTEGER NOT NULL,                 -- unix ms
  FOREIGN KEY (forked_from_id) REFERENCES studio_library_items(id) ON DELETE SET NULL
);

-- The library list is always team-scoped and ordered newest-first; this index backs it.
CREATE INDEX IF NOT EXISTS idx_studio_library_team
  ON studio_library_items(team_id, created_at DESC);
