-- 0077_stripe_webhook_events.sql (NO-OP: Schema already exists from 0060)
--
-- HISTORY: Migration 0060 created stripe_webhook_events table + indexes with bare
-- CREATE INDEX (no IF NOT EXISTS). This caused the migration chain to fail on
-- production where those indexes already existed, blocking 0078+.
--
-- RESOLUTION: This migration is intentionally empty (no-op). The schema exists in
-- production from 0060. D1 will mark this migration as applied, allowing the chain
-- to continue to 0078+.
--
-- If applying to a fresh database, 0060's CREATE INDEX statements will succeed
-- without issues (it has IF NOT EXISTS), making this marker unnecessary but harmless.
