// Content Queue — review drafts generated by the Content Engine cron.
// Inline edit (draft only), approve/reject (draft only), publish (approved only).

import { useState } from 'react'
import { useContentItems, type ContentItem } from '../../hooks/useMarketingApi'
import { Heading, Body, Card, Button, EmptyState, SkeletonCard } from '../../ui/components'

function StatusBadge({ status }: { status: ContentItem['status'] }) {
  const styles: Record<ContentItem['status'], string> = {
    draft: 'bg-pulse-100 text-pulse-600',
    approved: 'bg-blue-100 text-blue-700',
    rejected: 'bg-red-100 text-red-600',
    published: 'bg-green-100 text-green-600',
    failed: 'bg-red-100 text-red-700',
  }
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium capitalize ${styles[status]}`}>
      {status}
    </span>
  )
}

function PlatformBadge({ platform }: { platform: ContentItem['platform'] }) {
  return (
    <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-purple-100 text-purple-700 capitalize">
      {platform}
    </span>
  )
}

function ContentItemCard({
  item,
  onPatch,
  onApprove,
  onReject,
  onPublish,
}: {
  item: ContentItem
  onPatch: (id: string, fields: Partial<Pick<ContentItem, 'body' | 'script' | 'youtube_video_id'>>) => Promise<unknown>
  onApprove: (id: string) => Promise<unknown>
  onReject: (id: string) => Promise<unknown>
  onPublish: (id: string) => Promise<unknown>
}) {
  const [body, setBody] = useState(item.body ?? '')
  const [script, setScript] = useState(item.script ?? '')
  const [youtubeVideoId, setYoutubeVideoId] = useState(item.youtube_video_id ?? '')
  const [saving, setSaving] = useState(false)
  const [busy, setBusy] = useState(false)

  const editable = item.status === 'draft'
  const dirty =
    body !== (item.body ?? '') || script !== (item.script ?? '') || youtubeVideoId !== (item.youtube_video_id ?? '')

  async function save() {
    setSaving(true)
    const fields: Partial<Pick<ContentItem, 'body' | 'script' | 'youtube_video_id'>> = {}
    if (item.body !== null) fields.body = body
    if (item.script !== null) fields.script = script
    if (item.platform === 'youtube') fields.youtube_video_id = youtubeVideoId || null
    await onPatch(item.id, fields)
    setSaving(false)
  }

  return (
    <Card className="space-y-3">
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <div className="flex items-center gap-2">
          <PlatformBadge platform={item.platform} />
          <StatusBadge status={item.status} />
        </div>
        <span className="text-xs text-pulse-500 dark:text-[var(--text-muted)]">
          {new Date(item.generated_at).toLocaleString()}
        </span>
      </div>

      {item.body !== null && (
        <textarea
          value={body}
          onChange={(e) => setBody(e.target.value)}
          disabled={!editable}
          rows={4}
          className="w-full text-body-s border border-pulse-300 dark:border-[var(--color-border-strong)] rounded-md px-3 py-2 bg-white dark:bg-[var(--color-surface-elevated)] text-pulse-900 dark:text-[var(--text-primary)] disabled:opacity-60"
          aria-label="LinkedIn post body"
        />
      )}

      {item.script !== null && (
        <textarea
          value={script}
          onChange={(e) => setScript(e.target.value)}
          disabled={!editable}
          rows={6}
          className="w-full text-body-s border border-pulse-300 dark:border-[var(--color-border-strong)] rounded-md px-3 py-2 bg-white dark:bg-[var(--color-surface-elevated)] text-pulse-900 dark:text-[var(--text-primary)] disabled:opacity-60"
          aria-label="YouTube script"
        />
      )}

      {item.platform === 'youtube' && (
        <div>
          <label className="text-xs font-medium text-pulse-600 dark:text-[var(--text-muted)]" htmlFor={`yt-id-${item.id}`}>
            Uploaded YouTube video ID (required before publish)
          </label>
          <input
            id={`yt-id-${item.id}`}
            type="text"
            value={youtubeVideoId}
            onChange={(e) => setYoutubeVideoId(e.target.value)}
            disabled={!editable}
            placeholder="e.g. dQw4w9WgXcQ"
            className="mt-1 w-full text-body-s border border-pulse-300 dark:border-[var(--color-border-strong)] rounded-md px-3 py-2 bg-white dark:bg-[var(--color-surface-elevated)] text-pulse-900 dark:text-[var(--text-primary)] disabled:opacity-60"
          />
        </div>
      )}

      {item.failure_reason && (
        <Body size="s" className="text-signal-error">{item.failure_reason}</Body>
      )}

      <div className="flex items-center gap-2 flex-wrap">
        {editable && (
          <>
            <Button size="sm" variant="secondary" disabled={!dirty || saving} onClick={save}>
              {saving ? 'Saving…' : 'Save edits'}
            </Button>
            <Button
              size="sm"
              variant="primary"
              disabled={busy}
              onClick={async () => {
                setBusy(true)
                await onApprove(item.id)
                setBusy(false)
              }}
            >
              Approve
            </Button>
            <Button
              size="sm"
              variant="danger"
              disabled={busy}
              onClick={async () => {
                setBusy(true)
                await onReject(item.id)
                setBusy(false)
              }}
            >
              Reject
            </Button>
          </>
        )}
        {item.status === 'approved' && (
          <Button
            size="sm"
            variant="primary"
            disabled={busy || (item.platform === 'youtube' && !item.youtube_video_id)}
            onClick={async () => {
              setBusy(true)
              await onPublish(item.id)
              setBusy(false)
            }}
          >
            Publish
          </Button>
        )}
      </div>
    </Card>
  )
}

export default function ContentQueueTab() {
  const [statusFilter, setStatusFilter] = useState<string>('draft')
  const { items, loading, error, patchItem, approve, reject, publish } = useContentItems(
    statusFilter ? { status: statusFilter } : {},
  )

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <Heading level="m" className="border-l-4 border-teal-500 pl-3">Content Queue</Heading>
        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          className="text-body-s border border-pulse-300 dark:border-[var(--color-border-strong)] rounded-md px-3 py-1.5 bg-white dark:bg-[var(--color-surface-elevated)] text-pulse-900 dark:text-[var(--text-primary)]"
          aria-label="Filter by status"
        >
          <option value="draft">Draft</option>
          <option value="approved">Approved</option>
          <option value="rejected">Rejected</option>
          <option value="published">Published</option>
          <option value="failed">Failed</option>
          <option value="">All</option>
        </select>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <SkeletonCard key={i} className="h-48" />
          ))}
        </div>
      ) : error ? (
        <Body className="text-signal-error">{error}</Body>
      ) : items.length === 0 ? (
        <EmptyState title="No content items" description="The Content Engine cron hasn't generated anything matching this filter yet." />
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {items.map((item) => (
            <ContentItemCard
              key={item.id}
              item={item}
              onPatch={patchItem}
              onApprove={approve}
              onReject={reject}
              onPublish={publish}
            />
          ))}
        </div>
      )}
    </div>
  )
}
