/**
 * AIBadge — marks AI-touched content with a labelled pill.
 *
 * Variants:
 *   assisted  — AI helped shape this (default)
 *   generated — content was fully AI-generated
 *   analyzed  — content was AI-analyzed/summarized
 */

type AIBadgeVariant = 'assisted' | 'generated' | 'analyzed'

interface AIBadgeProps {
  variant?: AIBadgeVariant
  /** Override the visible label (falls back to per-variant default) */
  label?: string
  /** Extra Tailwind classes to append to the container */
  className?: string
}

const VARIANT_DEFAULTS: Record<AIBadgeVariant, { label: string; tooltip: string }> = {
  assisted:  { label: 'AI assisted',  tooltip: 'AI helped shape this content' },
  generated: { label: 'AI generated', tooltip: 'This content was fully generated by AI' },
  analyzed:  { label: 'AI analyzed',  tooltip: 'This content was summarized or analyzed by AI' },
}

export default function AIBadge({ variant = 'assisted', label, className = '' }: AIBadgeProps) {
  const defaults = VARIANT_DEFAULTS[variant]
  const visibleLabel = label ?? defaults.label

  return (
    <span
      className={[
        'inline-flex items-center gap-space-1 rounded-pill px-space-3 py-space-1',
        'bg-violet-100 text-violet-700 text-caption font-medium',
        'border border-violet-200',
        'dark:bg-violet-900/40 dark:text-violet-300 dark:border-violet-700',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      aria-label={visibleLabel}
      title={defaults.tooltip}
    >
      {/* Sparkle icon — decorative */}
      <svg
        aria-hidden="true"
        focusable="false"
        width="12"
        height="12"
        viewBox="0 0 24 24"
        fill="currentColor"
      >
        <path d="M12 2l2.09 6.26L20 10l-5.91 1.74L12 18l-2.09-5.26L4 11l5.91-1.74L12 2z" />
      </svg>
      {visibleLabel}
    </span>
  )
}
