// Marketing Review Dashboard — content items (drafts generated by the
// Content Engine, reviewed/edited/approved/rejected/published by the owner).

import { Hono } from 'hono'
import { z } from 'zod'
import { authMiddleware, type AuthVariables } from '../../middleware/auth'
import { marketingOwnerMiddleware, type MarketingOwnerVariables } from '../../middleware/marketing-owner'
import { validateBody } from '../../lib/request-validation'
import { recordAuditEvent } from '../../lib/audit'
import { publishContentItem } from '../../lib/marketing/publisher'
import type { Env } from '../../types'

type App = Hono<{ Bindings: Env; Variables: AuthVariables & MarketingOwnerVariables }>

interface ContentItemRow {
  id: string
  content_calendar_id: string
  platform: string
  status: string
  body: string | null
  script: string | null
  metadata: string
  video_asset_id: string | null
  youtube_video_id: string | null
  generated_at: number
  reviewed_at: number | null
  published_at: number | null
  platform_post_id: string | null
  failure_reason: string | null
  created_at: number
  updated_at: number
}

export function mountContentItemsRoutes(app: App) {
  app.get('/content-items', authMiddleware, marketingOwnerMiddleware, async (c) => {
    const trace_id = c.get('trace_id')
    const status = c.req.query('status')
    const platform = c.req.query('platform')
    const limit = Math.min(Math.max(Number(c.req.query('limit') ?? 50), 1), 200)

    const clauses: string[] = []
    const binds: unknown[] = []
    let i = 1
    if (status) {
      clauses.push(`status = ?${i++}`)
      binds.push(status)
    }
    if (platform) {
      clauses.push(`platform = ?${i++}`)
      binds.push(platform)
    }
    const where = clauses.length > 0 ? `WHERE ${clauses.join(' AND ')}` : ''
    binds.push(limit)

    const { results } = await c.env.DB.prepare(
      `SELECT * FROM content_items ${where} ORDER BY generated_at DESC LIMIT ?${i}`,
    )
      .bind(...binds)
      .all<ContentItemRow>()

    return c.json({ ok: true, data: { items: results ?? [] }, trace_id }, 200)
  })

  const PatchContentItem = z.object({
    body: z.string().max(10000).optional(),
    script: z.string().max(20000).optional(),
    metadata: z.record(z.string(), z.unknown()).optional(),
    youtube_video_id: z.string().max(64).nullable().optional(),
  })
  app.patch('/content-items/:id', authMiddleware, marketingOwnerMiddleware, async (c) => {
    const trace_id = c.get('trace_id')
    const id = c.req.param('id')
    const validated = await validateBody(c, PatchContentItem)
    if ('error' in validated) return validated.error

    const row = await c.env.DB.prepare(`SELECT id, status FROM content_items WHERE id = ?1`).bind(id).first<{ id: string; status: string }>()
    if (!row) return c.json({ ok: false, error: { code: 'not_found', message: 'Content item not found' }, trace_id }, 404)
    if (row.status !== 'draft') {
      return c.json({ ok: false, error: { code: 'conflict', message: 'Only draft items can be edited' }, trace_id }, 409)
    }

    const { body, script, metadata, youtube_video_id } = validated.data
    const sets: string[] = []
    const binds: unknown[] = []
    let i = 1
    if (body !== undefined) {
      sets.push(`body = ?${i++}`)
      binds.push(body)
    }
    if (script !== undefined) {
      sets.push(`script = ?${i++}`)
      binds.push(script)
    }
    if (metadata !== undefined) {
      sets.push(`metadata = ?${i++}`)
      binds.push(JSON.stringify(metadata))
    }
    if (youtube_video_id !== undefined) {
      sets.push(`youtube_video_id = ?${i++}`)
      binds.push(youtube_video_id)
    }
    if (sets.length === 0) {
      return c.json({ ok: false, error: { code: 'validation', message: 'No fields to update' }, trace_id }, 400)
    }
    const now = Date.now()
    sets.push(`updated_at = ?${i++}`)
    binds.push(now)
    binds.push(id)
    await c.env.DB.prepare(`UPDATE content_items SET ${sets.join(', ')} WHERE id = ?${i}`).bind(...binds).run()
    await recordAuditEvent(c, { action: 'marketing.content_item_edit', subject_type: 'content_item', subject_id: id, trace_id })
    return c.json({ ok: true, data: { id, updated_at: now }, trace_id }, 200)
  })

  app.post('/content-items/:id/approve', authMiddleware, marketingOwnerMiddleware, async (c) => {
    const trace_id = c.get('trace_id')
    const id = c.req.param('id')
    const row = await c.env.DB.prepare(`SELECT id, status FROM content_items WHERE id = ?1`).bind(id).first<{ id: string; status: string }>()
    if (!row) return c.json({ ok: false, error: { code: 'not_found', message: 'Content item not found' }, trace_id }, 404)
    if (row.status !== 'draft') {
      return c.json({ ok: false, error: { code: 'conflict', message: `Only draft items can be approved (status=${row.status})` }, trace_id }, 409)
    }
    const now = Date.now()
    await c.env.DB.prepare(`UPDATE content_items SET status = 'approved', reviewed_at = ?1, updated_at = ?1 WHERE id = ?2`).bind(now, id).run()
    await recordAuditEvent(c, { action: 'marketing.content_item_approve', subject_type: 'content_item', subject_id: id, trace_id })
    return c.json({ ok: true, data: { id, status: 'approved' }, trace_id }, 200)
  })

  app.post('/content-items/:id/reject', authMiddleware, marketingOwnerMiddleware, async (c) => {
    const trace_id = c.get('trace_id')
    const id = c.req.param('id')
    const row = await c.env.DB.prepare(`SELECT id, status FROM content_items WHERE id = ?1`).bind(id).first<{ id: string; status: string }>()
    if (!row) return c.json({ ok: false, error: { code: 'not_found', message: 'Content item not found' }, trace_id }, 404)
    if (row.status !== 'draft') {
      return c.json({ ok: false, error: { code: 'conflict', message: `Only draft items can be rejected (status=${row.status})` }, trace_id }, 409)
    }
    const now = Date.now()
    await c.env.DB.prepare(`UPDATE content_items SET status = 'rejected', reviewed_at = ?1, updated_at = ?1 WHERE id = ?2`).bind(now, id).run()
    await recordAuditEvent(c, { action: 'marketing.content_item_reject', subject_type: 'content_item', subject_id: id, trace_id })
    return c.json({ ok: true, data: { id, status: 'rejected' }, trace_id }, 200)
  })

  app.post('/content-items/:id/publish', authMiddleware, marketingOwnerMiddleware, async (c) => {
    const trace_id = c.get('trace_id')
    const id = c.req.param('id')
    const kv = c.env.INTEGRATIONS_KV
    if (!kv) return c.json({ ok: false, error: { code: 'unavailable', message: 'INTEGRATIONS_KV not configured' }, trace_id }, 503)

    const result = await publishContentItem(c.env, c.env.DB, kv, id)
    await recordAuditEvent(c, {
      action: 'marketing.content_item_publish',
      subject_type: 'content_item',
      subject_id: id,
      after_snapshot: result,
      trace_id,
    })
    if (!result.ok) {
      return c.json({ ok: false, error: { code: 'publish_failed', message: result.reason }, trace_id }, 502)
    }
    return c.json({ ok: true, data: { id, status: 'published', platform_post_id: result.platformPostId }, trace_id }, 200)
  })
}
